# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# Full reference for Standard Spring Boot properties is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
# set -Dspring.profiles.active=<dev|sit|int> as JVM argument to run in desired profile
# If no profile is specified explicitly, application will fall back to default profile, which is "local"

spring:
  application:
    name: spark-mongodb-arangodb-demo
  devtools:
    add-properties: false
    restart:
      enabled: false
      exclude: logs/*,application.log,*.log,*.log.*

  main:
    log-startup-info: true
  redis:
    uri: ${REDIS_URL:localhost:6379}

#------------------------- Spark MongoDB configuration -------------------------
spark:
  app-name: ${spring.application.name}
  master: local[*]
  executor:
    instances: 3
  mongo:
    url: ${MONGODB_URL:mongodb://localhost:27017}
    feature:
      database: ${FEATURES_DATABASE:feature-repo}
      collection: ${FEATURES_COLLECTION:customer_product}
    inference:
      database: ${INFERENCE_DATABASE:inference-repo}
      collection: ${INFERENCE_COLLECTION:customer_product}
    label:
      database: ${LABEL_DATABASE:label-repo}
      collection: ${LABEL_COLLECTION:customer_product}
  arango:
    endpoints: ${ARANGODB_URL:localhost:8529}
    database: ${ARANGODB_DATABASE:test_db}
    username: ${ARANGODB_PASSWORD:root}
    password: ${ARANGODB_PASSWORD:admin}
    ssl-enabled: false
    ssl-cert-value: ""

logging:
  level:
    ROOT: info
    '[org.mongodb.driver]': warn

    web: debug
debug: false

# ===================================================================
# Application specific properties
# Add your own application properties here
# ===================================================================
