logging:
  logback:
    rollingpolicy:
      clean-history-on-start: true
  file:
    path: logs
    name: ${logging.file.path}/application.log
  level:
    ROOT: info
debug: false

# ===================================================================
# Application specific properties
# Add your own application properties here
# ===================================================================

        