#spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://devuser:devuser@cluster0.cnatwcf.mongodb.net/?retryWrites=true&w=majority
#      database: product_db
#      auto-index-creation: true
#      uuid-representation: standard

server:
  port: 8080
  #servlet:
  #context-path:

logging:
  logback:
    rollingpolicy:
      clean-history-on-start: true
  file:
    path: logs
    name: ${logging.file.path}/application.log
  level:
    ROOT: info
debug: false

  # ===================================================================
  # Application specific properties
  # Add your own application properties here
  # ===================================================================

        